mybatis-plus:
    mapper-locations: classpath:/mapper/**.xml
server:
    port: 8080
spring:
    application:
        name: labdemo
    shardingsphere:
        datasource:
            names: test1,test2 # 指定数据源名字，多数据源以逗号分隔
            test1:
                type: com.alibaba.druid.pool.DruidDataSource
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://localhost:3306/test1?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
                username: root
                password: 123456

            test2:
                type: com.alibaba.druid.pool.DruidDataSource
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://localhost:3306/test2?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
                username: root
                password: 123456

        sharding:
            default-data-source-name: test2 # 默认数据源
            tables: #　具体分片规则配置
                t_product: #逻辑表名
                    key-generator:
                        column: id
                        # 使用雪花算法生成id
                        type: SNOWFLAKE
                    actual-data-nodes: test$->{1..2}.t_product # 实际的数据节点(数据源名.逻辑表名)
                    databaseStrategy: # sharding 规 则
                        inline:
                            shardingColumn: id # 列 名
                            algorithmExpression: test${id % 2 + 1}  # 例如：id=1 时表示 test2
        props:
            sql.show: true # 是否开启SQL显示
    main:
        allow-bean-definition-overriding: true
    redis:
        host: 127.0.0.1
        pool:
            max-active: 8
            max-idle: 8
            max-wait: -1
            min-idle: 0
        port: 6379
    thymeleaf:
        cache: false
        check-template: true
        check-template-location: true
        content-type: text/html
        enabled: true
        encoding: UTF-8
        excluded-view-names: ''
        mode: HTML
        prefix: classpath:/templates/
        suffix: .html
